Make sure postinst still running, so not as damage to dpkg

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -9,12 +9,11 @@ VERSION="0.36.0"
 GECKODRIVER="usr/share/QRLJacker/geckodriver/"
 
 if [ -e "$GECKODRIVER/geckodriver-$VERSION-$ARCH" ];
-	ln -s $GECKODRIVER/geckodriver-$VERSION-$ARCH /usr/local/bin/geckodriver
-	ln -s $GECKODRIVER/geckodriver-$VERSION-$ARCH /usr/local/bin/geckodriver
-	ln -s $GECKODRIVER/geckodriver-$VERSION-$ARCH /usr/bin/geckodriver
+	ln -s $GECKODRIVER/geckodriver-$VERSION-$ARCH /usr/local/bin/geckodriver || echo "Failed to create symlink"
+	ln -s $GECKODRIVER/geckodriver-$VERSION-$ARCH /usr/local/bin/geckodriver || echo "Failed to create symlink"
+	ln -s $GECKODRIVER/geckodriver-$VERSION-$ARCH /usr/bin/geckodriver || echo "Failed to create symlink"
 else
-	echo "Error: $GECKODRIVER/geckodriver-$VERSION-$ARCH is MiSSING!"
-	exit 1
+	echo "Error: $GECKODRIVER/geckodriver-$VERSION-$ARCH is MiSSING!" > /tmp/qrljacking-failed.txt
 fi
 
 ### Give permissing to qrljacker
